apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tjenestepensjon-simulering
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{version}}
  port: 8080
  ingresses:
    - https://tjenestepensjon-simulering.nais.adeo.no
  liveness:
    path: isAlive
  readiness:
    path: isReady
  vault:
    enabled: true
#    paths:
#     - kvPath: /kv/prod/fss/tjenestepensjon-simulering/default
#       mountPath: /var/run/secrets/nais.io/vault
#     - kvPath: /maskinporten/data/dev/creds/tjenestepensjon-simulering
#       mountPath: /var/run/secrets/nais.io/vault/jwks
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
  prometheus:
    enabled: true
    path: actuator/prometheus