apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tjenestepensjon-simulering
  namespace: default
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://tjenestepensjon-simulering.nais.preprod.local
  liveness:
    path: isAlive
    initialDelay: 30
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: isReady
    initialDelay: 30
    periodSeconds: 1
    failureThreshold: 60
  vault:
    enabled: true
    paths:
      - kvPath: /maskinporten/data/dev/creds/tjenestepensjon-simulering
        mountPath: /var/run/secrets/nais.io/vault/jwks
  webproxy: true
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: actuator/prometheus