apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tjenestepensjon-simulering
  namespace: default
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://tjenestepensjon-simulering.nais.adeo.no
  liveness:
    path: isAlive
  readiness:
    path: isReady
  vault:
    enabled: true
    paths:
     - kvPath: /maskinporten/data/prod/creds/tjenestepensjon-simulering
       mountPath: /var/run/secrets/nais.io/vault/jwks
  spec:
    webproxy: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
  prometheus:
    enabled: true
    path: actuator/prometheus