apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tjenestepensjon-simulering
  namespace: default
  labels:
    team: teampeon
spec:
  image: {{version}}
  port: 8080
  ingresses:
    - https://tjenestepensjon-simulering.nais.preprod.local
  liveness:
    path: isAlive
  readiness:
    path: isReady
  vault:
    enabled: true
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: actuator/prometheus