apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tjenestepensjon-simulering
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
spec:
  image: {{ image }}
  resources:
    limits:
      memory: 916Mi
    requests:
      cpu: 50m
      memory: 458Mi
  port: 8080
  webproxy: true
  ingresses:
    - https://tjenestepensjon-simulering.intern.dev.nav.no
    - https://tjenestepensjon-simulering.dev.intern.nav.no
  accessPolicy:
    inbound:
      rules:
        - application: pensjon-pen-q0
          namespace: pensjon-q0
        - application: pensjon-pen-q1
          namespace: pensjon-q1
        - application: pensjon-pen-q2
          namespace: pensjon-q2
        - application: pensjon-pen-q5
          namespace: pensjon-q5
        - application: pensjon-testdata-server-q2
          namespace: pensjontestdata
    outbound:
      rules:
        - application: tp-q2
          namespace: pensjonsamhandling
          cluster: dev-fss
        - application: pensjon-opptjening-afp-api
          namespace: pensjonopptjening
          cluster: dev-gcp
        - application: pensjon-pen-q2
          namespace: pensjon-q2
          cluster: dev-fss
  azure:
    application:
      enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "klp:pensjonsimulering"
        - name: "nav:pensjon/v1/tpregisteret"
  liveness:
    path: actuator/health/liveness
    initialDelay: 30
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
  startup:
    path: actuator/health/readiness
    initialDelay: 30
    failureThreshold: 30
    periodSeconds: 5
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/fss/tjenestepensjon-simulering/pensjonskalkulator
        mountPath: /var/run/secrets/nais.io/vault
  replicas:
    min: 2
    max: 2
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: preprod
    - name: provider_uri
      value: https://pep-gw-q1.oera-q.local:9443/ekstern-pensjon-tjeneste-tjenestepensjonSimuleringWeb/sca/TjenestepensjonSimuleringWSEXP
    - name: sts_url
      value: https://security-token-service.nais.preprod.local
    - name: tp_url
      value: https://tp-q2.dev.intern.nav.no
    - name: tp_scope
      value: api://dev-fss.pensjonsamhandling.tp-q2/.default
    - name: afp_beholdning_url
      value: https://pensjon-opptjening-afp-api.intern.dev.nav.no
    - name: afp_beholdning_scope
      value: api://dev-gcp.pensjonopptjening.pensjon-opptjening-afp-api/.default
    - name: pen_url
      value: https://pensjon-pen-q2.nais.preprod.local/pen/springapi
    - name: pen_scope
      value: api://dev-fss.pensjon-q2.pensjon-pen-q2/.default
  prometheus:
    enabled: true
    path: actuator/prometheus
