apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tjenestepensjon-simulering
  namespace: pensjonskalkulator
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "256M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
    config.linkerd.io/proxy-outbound-connect-timeout: "3s"
  labels:
    team: pensjonskalkulator
spec:
  image: {{ image }}
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 50m
      memory: 1024Mi
  port: 8080
  ingresses:
    - https://tjenestepensjon-simulering-gcp.intern.dev.nav.no
  accessPolicy:
    inbound:
      rules:
        - application: pensjon-pen-q0
          namespace: pensjon-q0
          cluster: dev-fss
        - application: pensjon-pen-q1
          namespace: pensjon-q1
          cluster: dev-fss
        - application: pensjon-pen-q2
          namespace: pensjon-q2
          cluster: dev-fss
        - application: pensjon-pen-q5
          namespace: pensjon-q5
          cluster: dev-fss
        - application: pensjon-testdata-server-q2
          namespace: pensjontestdata
          cluster: dev-fss
        - application: pensjonskalkulator-backend
          namespace: pensjonskalkulator
          cluster: dev-gcp
        - application: penbatch-q0
          namespace: pensjon-batch
          cluster: dev-fss
        - application: penbatch-q1
          namespace: pensjon-batch
          cluster: dev-fss
        - application: penbatch-q2
          namespace: pensjon-batch
          cluster: dev-fss
        - application: penbatch-q5
          namespace: pensjon-batch
          cluster: dev-fss
        - application: pensjonssimulator
    outbound:
      rules:
        - application: tp-q2
          namespace: pensjonsamhandling
          cluster: dev-fss
        - application: pensjon-opptjening-afp-api
          namespace: pensjonopptjening
        - application: pensjon-pen-q2
          namespace: pensjon-q2
          cluster: dev-fss
        - application: pensjon-selvbetjening-fss-gateway
          namespace: pensjonselvbetjening
          cluster: dev-fss
      external:
        - host: pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
        - host: pensjon-pen-q2.dev-fss-pub.nais.io
        - host: tp-api-q2.dev-fss-pub.nais.io
        - host: api.preprod.spk.no
        - host: api.test.spk.no
        - host: api-test.klp.no
  azure:
    application:
      enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "klp:oftp/simulering"
        - name: "klp:pensjonsimulering"
        - name: "nav:pensjon/v1/tpregisteret"
        - name: "spk:nav"
  liveness:
    path: actuator/health/liveness
    initialDelay: 30
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
  startup:
    path: actuator/health/readiness
    initialDelay: 30
    failureThreshold: 30
    periodSeconds: 5
  replicas:
    min: 2
    max: 2
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: provider_uri
      value: https://pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io/ekstern-pensjon-tjeneste-tjenestepensjonSimuleringWeb/sca/TjenestepensjonSimuleringWSEXP
    - name: tp_url
      value: https://tp-api-q2.dev-fss-pub.nais.io
    - name: tp_scope
      value: api://dev-fss.pensjonsamhandling.tp-q2/.default
    - name: afp_beholdning_url
      value: http://pensjon-opptjening-afp-api.pensjonopptjening
    - name: afp_beholdning_scope
      value: api://dev-gcp.pensjonopptjening.pensjon-opptjening-afp-api/.default
    - name: pen_url
      value: https://pensjon-pen-q2.dev-fss-pub.nais.io/pen/springapi
    - name: pen_scope
      value: api://dev-fss.pensjon-q2.pensjon-pen-q2/.default
    - name: pen_fss_gateway_url
      value: https://pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
    - name: pen_fss_gateway_scope
      value: api://dev-fss.pensjonselvbetjening.pensjon-selvbetjening-fss-gateway/.default
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: deployment.environment.name=q2
  envFrom:
    - secret: tjenestepensjon-simulering-unleash-api-token
  prometheus:
    enabled: true
    path: actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
