apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tjenestepensjon-simulering
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
spec:
  image: {{ image }}
  port: 8080
  webproxy: true
  ingresses:
    - https://tjenestepensjon-simulering.nais.preprod.local
    - https://tjenestepensjon-simulering.dev.intern.nav.no
  accessPolicy:
    inbound:
      rules:
        - application: pensjon-pen-q0
          namespace: pensjon-q0
        - application: pensjon-pen-q1
          namespace: pensjon-q1
        - application: pensjon-pen-q2
          namespace: pensjon-q2
        - application: pensjon-pen-q5
          namespace: pensjon-q5
    outbound:
      rules:
        - application: tp-q1
          namespace: pensjonsamhandling
          cluster: dev-fss
  azure:
    application:
      enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "klp:pensjonsimulering"
        - name: "nav:pensjon/v1/tpregisteret"
  liveness:
    path: actuator/health/liveness
    initialDelay: 30
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
  startup:
    path: actuator/health/readiness
    initialDelay: 30
    failureThreshold: 30
    periodSeconds: 5
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/fss/tjenestepensjon-simulering/pensjonskalkulator
        mountPath: /var/run/secrets/nais.io/vault
  replicas:
    min: 2
    max: 2
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: preprod
  prometheus:
    enabled: true
    path: actuator/prometheus
