apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tjenestepensjon-simulering
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
spec:
  image: {{ image }}
  port: 8080
  webproxy: true
  ingresses:
    - https://tjenestepensjon-simulering.nais.adeo.no
  accessPolicy:
    inbound:
      rules:
        - application: pensjon-pen
          namespace: pensjondeployer
    outbound:
      rules:
        - application: tp
          namespace: pensjonsamhandling
          cluster: prod-fss
  azure:
    application:
      enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "klp:pensjonsimulering"
        - name: "nav:pensjon/v1/tpregisteret"
  liveness:
    path: actuator/health/liveness
    initialDelay: 30
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
  startup:
    path: actuator/health/readiness
    initialDelay: 30
    failureThreshold: 30
    periodSeconds: 5
  vault:
    enabled: true
    paths:
      - kvPath: /kv/prod/fss/tjenestepensjon-simulering/pensjonskalkulator
        mountPath: /var/run/secrets/nais.io/vault
  replicas:
    min: 2
    max: 2
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: provider_uri
      value: https://pep-gw.oera.no:9443/ekstern-pensjon-tjeneste-tjenestepensjonSimuleringWeb/sca/TjenestepensjonSimuleringWSEXP
    - name: sts_url
      value: https://security-token-service.nais.adeo.no
    - name: tp_url
      value: https://tp.nais.adeo.no
    - name: tp_scope
      value: api://prod-fss.pensjonsamhandling.tp/.default
  prometheus:
    enabled: true
    path: actuator/prometheus
