apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tjenestepensjon-simulering
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://tjenestepensjon-simulering.nais.adeo.no
  accessPolicy:
    inbound:
      rules:
        - application: pensjon-pen
          namespace: pensjondeployer
    outbound:
      rules:
        - application: tp
          namespace: pensjonsamhandling
          cluster: prod-fss
  azure:
    application:
      enabled: true
  liveness:
    path: actuator/health/liveness
    initialDelay: 30
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
  startup:
    path: actuator/health/readiness
    initialDelay: 30
    failureThreshold: 30
    periodSeconds: 5
  vault:
    enabled: true
    paths:
      - kvPath: /kv/prod/fss/tjenestepensjon-simulering/pensjonsamhandling
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /maskinporten/data/prod/creds/tjenestepensjon-simulering
        mountPath: /var/run/secrets/nais.io/vault/jwks
  replicas:
    min: 1
    max: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  prometheus:
    enabled: true
    path: actuator/prometheus
