apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tjenestepensjon-simulering
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
spec:
  image: {{ image }}
  resources:
    limits:
      memory: 1088Mi
    requests:
      cpu: 100m
      memory: 544Mi
  port: 8080
  webproxy: true
  ingresses:
    - https://tjenestepensjon-simulering.intern.nav.no
  accessPolicy:
    inbound:
      rules:
        - application: pensjon-pen
          namespace: pensjondeployer
        - application: pensjonskalkulator-backend
          namespace: pensjonskalkulator
          cluster: prod-gcp
        - application: penbatch
          namespace: pensjon-batch
    outbound:
      rules:
        - application: tp
          namespace: pensjonsamhandling
          cluster: prod-fss
        - application: pensjon-opptjening-afp-api
          namespace: pensjonopptjening
          cluster: prod-gcp
        - application: pensjon-pen
          namespace: pensjondeployer
          cluster: prod-fss
  azure:
    application:
      enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "klp:pensjonsimulering"
        - name: "nav:pensjon/v1/tpregisteret"
  liveness:
    path: actuator/health/liveness
    initialDelay: 30
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
  startup:
    path: actuator/health/readiness
    initialDelay: 30
    failureThreshold: 30
    periodSeconds: 5
  vault:
    enabled: true
    paths:
      - kvPath: /kv/prod/fss/tjenestepensjon-simulering/pensjonskalkulator
        mountPath: /var/run/secrets/nais.io/vault
  replicas:
    min: 2
    max: 2
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: provider_uri
      value: https://pep-gw.oera.no:9443/ekstern-pensjon-tjeneste-tjenestepensjonSimuleringWeb/sca/TjenestepensjonSimuleringWSEXP
    - name: sts_url
      value: https://security-token-service.nais.adeo.no
    - name: tp_url
      value: https://tp.nais.adeo.no
    - name: tp_scope
      value: api://prod-fss.pensjonsamhandling.tp/.default
    - name: afp_beholdning_url
      value: https://pensjon-opptjening-afp-api.intern.nav.no
    - name: afp_beholdning_scope
      value: api://prod-gcp.pensjonopptjening.pensjon-opptjening-afp-api/.default
    - name: pen_url
      value: https://pensjon-pen.nais.adeo.no/pen/springapi
    - name: pen_scope
      value: api://prod-fss.pensjondeployer.pensjon-pen/.default
    - name: pen_fss_gateway_url
      value: https://pensjon-selvbetjening-fss-gateway.prod-fss-pub.nais.io
    - name: pen_fss_gateway_scope
      value: api://prod-fss.pensjonselvbetjening.pensjon-selvbetjening-fss-gateway/.default
  prometheus:
    enabled: true
    path: actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"