apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: tjenestepensjon-simulering
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: pensjonskalkulator
  secretName: tjenestepensjon-simulering-unleash-api-token
  environment: production