management:
  prometheus.metrics.export.enabled: true
  endpoint.health.probes.enabled: true
  endpoints.web.exposure.include: prometheus, health
  metrics.use-global-registry: true

spring:
  jackson:
    mapper:
      accept-case-insensitive-enums: true
      accept-case-insensitive-values: true
simulering:
  security:
    issuers: https://localhost,https://localhost
provider:
  uri: http://localhost:9080/ekstern-pensjon-tjeneste-tjenestepensjonSimuleringWeb/sca/TjenestepensjonSimuleringWSEXP

maskinporten:
  token-endpoint-url: ${MASKINPORTEN_TOKEN_ENDPOINT:https://test.maskinporten.no}
  client-id: ${MASKINPORTEN_CLIENT_ID:clientId}
  client-jwk: ${MASKINPORTEN_CLIENT_JWK:clientJwk}
  scope: ${MASKINPORTEN_SCOPES:"nav:scope:no"}
  issuer: ${MASKINPORTEN_ISSUER:https://test.maskinporten.no}

tjenestepensjon:
 url: http://nav.no/ekstern/pensjon/tjenester/tjenestepensjonSimulering/v1/TjenestepensjonSimulering/simulerOffentligTjenestepensjonRequest
stillingsprosent:
  url: http://nav.no/ekstern/pensjon/tjenester/tjenestepensjonSimulering/v1/TjenestepensjonSimulering/hentStillingsprosentListeRequest
security:
  context:
    url: http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd
SERVICE_USER: serviceuser
SERVICE_USER_PASSWORD: password
azure:
  app:
    client:
      id: ${AZURE_APP_CLIENT_ID:bogus}
    well-known-url: ${AZURE_APP_WELL_KNOWN_URL:https://localhost:8080/bogus}
  openid-config-issuer: ${AZURE_OPENID_CONFIG_ISSUER:https://localhost:8080/bogus}
sts:
  url: http://localhost:8080
tp:
  url: http://localhost:8080
  scope: api://bogus
afp:
  beholdning:
    url: http://localhost:8080
    scope: api://bogus
pen:
  url: http://localhost:8080
  scope: api://bogus
  fss:
    gateway:
      url: http://localhost:8080
      scope: api://bogus
oftp:
  2025:
    klp:
      endpoint:
        url: https://api.klp.no
        maskinportenscope: klp:oftp/simulering
    spk:
      endpoint:
        url: https://api.prod.spk.no
        maskinportenscope: spk:nav
  before2025:
    spk:
      endpoint:
        url: https://api.prod.spk.no
        maskinportenscope: spk:nav
unleash:
  server:
    api:
      url: ${UNLEASH_SERVER_API_URL:https://pensjonskalkulator-unleash-api.nav.cloud.nais.io}
      token: ${UNLEASH_SERVER_API_TOKEN:unleashToken}
  toggle:
    interval: ${UNLEASH_TOGGLE_INTERVAL:60}
nais:
  cluster:
    name: ${NAIS_CLUSTER_NAME:local}
  app:
    name: ${NAIS_APP_NAME:tjenestepensjon-simulering}