logging.level:
  no.nav.tjenestepensjon: DEBUG
  org.springframework:
    security.oauth2: DEBUG
    ws:
      web: DEBUG
      client.MessageTracing: DEBUG
  com.microsoft.aad: DEBUG

simulering.security.issuers: ${AZURE_OPENID_CONFIG_ISSUER},https://security-token-service.nais.preprod.local,https://security-token-service-t4.nais.preprod.local,https://navtestb2c.b2clogin.com/d38f25aa-eab8-4c50-9f28-ebf92c1256f2/v2.0/
klp:
  name: KLP
  implementation: REST
  simuleringUrl: https://partner-gw-test2.klp.no/api/pensjonsimulering
  stillingsprosentUrl: https://partner-gw-stage.klp.no/navs-ws-gateway/inbound/simuleretjenestepensjon
spk:
  name: SPK
  implementation: REST
  simuleringUrl: https://api.preprod.spk.no/medlem/pensjon/prognose/v1
  stillingsprosentUrl: https://partner-gw-test.spk.no/nav/SimulereTjenestepensjon
storebrand:
  name: STOREBRAND
  implementation: SOAP
  simuleringUrl: https://b2b-t.storebrand.no/nav/SimulerTP
  stillingsprosentUrl: https://b2b-t.storebrand.no/nav/SimulerTP
gabler:
  name: GABLER
  implementation: SOAP
  simuleringUrl: https://elsam.gabler.no/elsam.svc
  stillingsprosentUrl: https://elsam.gabler.no/elsam.svc
opf:
  name: OPF
  implementation: SOAP
  simuleringUrl: https://partner-gw.opf.no/Elsam.svc
  stillingsprosentUrl: https://partner-gw.opf.no/Elsam.svc
