MASKINPORTEN_URL: https://maskinporten.no
STS_URL: https://security-token-service.nais.adeo.no
TP_URL: https://tp-api.prod-fss-pub.nais.io
TP_CONFIG_URL: https://tpconfig.nais.adeo.no

logging.level:
  no.nav.tjenestepensjon: DEBUG
  org.springframework.security: WARN
