version: 2.1
orbs:
  nais: 'navikt/nais-deployment@1.4.1'
jobs:
  build_and_release:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run: mvn clean install
      - nais/docker-deploy:
          image: navikt/tjenestepensjon-simulering
workflows:
  version: 2
  deploy-docker-and-nais:
    jobs:
      - build_and_release:
          context: NAIS deployment
          filters:
            branches:
              only:
                - master
      - nais/deploy:
          name: Deploy dev
          repo: navikt/tjenestepensjon-simulering
          image: navikt/tjenestepensjon-simulering
          github-app-id: 23087
          nais-template: nais-dev.yaml
          environment: dev-fss
          team: teampeon
          build-and-push-docker-image: false
          requires:
            - build_and_release
          filters:
            branches:
              only:
                - master
      - nais/deploy:
          name: Deploy prod
          repo: navikt/tjenestepensjon-simulering
          image: navikt/tjenestepensjon-simulering
          github-app-id: 23087
          nais-template: nais-prod.yaml
          environment: prod-fss
          team: teampeon
          build-and-push-docker-image: false
          requires:
            - build_and_release
          filters:
            branches:
              only:
                - master
