version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn clean install
      - run:
          name: release
          command: |
            if [ -z "${CIRCLE_PULL_REQUEST}" ]; then
              docker build . -t navikt/tjenestepensjon-simulering:${CIRCLE_SHA1}
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              docker push navikt/tjenestepensjon-simulering:${CIRCLE_SHA1}
            fi
  deploy:
    docker:
      - image: navikt/deployment-cli:v0.1.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy to preprod
          command: |
            sed -i 's/latest/${CIRCLE_SHA1}/' nais.yaml
            echo $GITHUB_KEY | tr '_' '\n' > github.pem
            deployment-cli deploy create --environment=dev-fss --repository=navikt/tjenestepensjon-simulering --team=teampeon -r=nais.yaml --version=${CIRCLE_SHA1} --appid=23087 --key=github.pem
            rm github.pem
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master