version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/tjenestepensjon-simulering
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn clean install
      - run:
          name: release
          command: |
            if [ -z "${CIRCLE_PULL_REQUEST}" ] && [ "${CIRCLE_BRANCH}" = "master" ]; then
              docker build . -t navikt/tjenestepensjon-simulering:${CIRCLE_SHA1}
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              docker push navikt/tjenestepensjon-simulering:${CIRCLE_SHA1}
            fi