version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn clean install
      - run:
          name: github creds
          command: |
            git clone https://github.com/navikt/github-apps-support.git
            export PATH=`pwd`/github-apps-support/bin:$PATH
            echo "$GITHUB_KEY" | tr '_' '\n' > peonci.key
            export GITHUB_APP_TOKEN=$(generate-installation-token.sh `generate-jwt.sh peonci.key 23087`)
            echo -e "machine api.github.com login x-access-token password $GITHUB_APP_TOKEN" > ~/.netrc
            rm peonci.key
      - run:
          name: release
          command: |
            if [ -z "${CIRCLE_PULL_REQUEST}" ] && [ "${CIRCLE_BRANCH}" = "master" ]; then
              docker build . -t navikt/tjenestepensjon-simulering:${CIRCLE_SHA1}
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              docker push navikt/tjenestepensjon-simulering:${CIRCLE_SHA1}
            fi
      - run:
          name: deploy to preprod
          command: |
            curl -i \
                -X POST \
                -d '{
                     "ref": "'"${CIRCLE_SHA1}"'",
                     "description": "",
                     "environment": "dev-fss",
                     "required_contexts": [],
                     "payload": {
                       "version": [1, 0, 0],
                       "team": "teampeon",
                       "kubernetes": {
                         "resources": ['"$(cat nais-dev.json | jq '.spec.image = "'navikt/tjenestepensjon-simulering:${CIRCLE_SHA1}'"')"']
                       }
                     }
                   }' \
                -H "Accept: application/vnd.github.ant-man-preview+json" \
                -u "$GITHUB_USERNAME":"$GITHUB_TOKEN" \
                https://api.github.com/repos/navikt/tjenestepensjon-simulering/deployments
