version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn clean install
      - run:
          name: release
          command: |
            docker build . -t navikt/tjenestepensjon-simulering:${CIRCLE_SHA1}
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push navikt/tjenestepensjon-simulering:${CIRCLE_SHA1}
  deploy:
    docker:
      - image: navikt/deployment-cli:0.1.6
    steps:
      - run:
          name: deploy to dev
          command: deployment-cli deploy create --cluster=dev-fss --repository=navikt/tjenestepensjon-simulering --team=teampeon -r=nais.yaml --version=${CIRCLE_SHA1}
workflows:
  version: 2.1
  build_and_release:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
