name: Build

on:
  push:
    branches-ignore:
      - main
      - sandbox

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: write
      security-events: write
    steps:
      # Checkout
      - uses: actions/checkout@v5
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew clean build -Dorg.gradle.jvmargs="-Xmx3072m -XX:MaxMetaspaceSize=512m"
        env:
          GITHUB_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:java"
