name: Deploy tjenestepensjon-simulering to Prod

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Which version to deploy (e.g. 2020.01.01-12.55-a1b2c3d4e5f6)"
        required: true

jobs:
  prod_deploy:
    name: Deploy tjenestepensjon-simulering to Prod
    permissions:
      contents: "read"
      checks: "write"
      id-token: "write"
      packages: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Input
        run: echo "version = ${{ github.event.inputs.version }}"
      - name: Deploy tjenestepensjon-simulering to prod-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: .nais/nais-prod.yaml
          IMAGE: "ghcr.io/${{ github.repository }}/tjenestepensjon-simulering:${{ github.event.inputs.version }}"
          TEAM: pensjonskalkulator
