name: Deploy rollback version

on:
  push:
    branches:
      - rollback-latest

jobs:
  build-and-release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      # Build
      - name: Build
        run: mvn clean install
      # Release
      - name: Create tag
          NAME: tjenestepensjon-simulering
        run: |
          echo "docker.pkg.github.com"/"$GITHUB_REPOSITORY"/"$NAME" > .docker_image
          echo "$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" > .docker_tag
          echo "::set-env name=IMAGE::$(cat .docker_image):$(cat .docker_tag)"
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
  deploy:
    name: Deploy to dev-fss
    needs: build-and-release
    if: github.ref == 'refs/heads/rollback-latest'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais-dev.yaml
